name: build-base

# Were we can define the inputs that our action will accept
inputs:
  dbpath: 
    required: true
    type: string
  
  # Google Cloud Artifact registry full tag used by docker
  # In the form {region}/{project}/{registry}
  ghcrtag:
    required: true
    type: string

  # Docker image tag
  imgtag:
    required: true
    type: string
  
  keyfile:
    required: true
    type: string



runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
  - name: Build base image
    working-directory: DruidsCornerAPI 
    shell: bash
    run : |
      docker build -f Dockerfile.base . -t druidscornerapi-base --build-arg SA_KEYFILE='${{ inputs.keyfile }}' --build-arg BUCKET_DBPATH=${{ inputs.dbpath }}
      docker tag druidscornerapi-base ${{ inputs.ghcrtag }}:${{ inputs.imgtag }}

  - name: Publish image
    shell: bash
    run : |
      docker push ${{ inputs.ghcrtag }}:${{ inputs.imgtag }}
    