name: build-base

# Were we can define the inputs that our action will accept
inputs:
  dbpath: 
    required: true
    type: string
  
  # Google Cloud Artifact registry full tag used by docker
  # In the form {region}/{project}/{registry}
  gcrtag:
    required: true
    type: string

  # Docker image tag
  imgtag:
    required: true
    type: string
  



runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
  - name: Build base image
    working-directory: DruidsCornerAPI 
    run : |
      docker build -f Dockerfile.base . -t druidscornerapi-base --build-arg SA_KEYFILE='${{ secrets.DRUIDS_CORNER_CLOUD_CICD_SA_KEYFILE }}' --build-arg BUCKET_DBPATH='${{ inputs.db-path }}'
      docker tag druidscornerapi-base ${{ inputs.gcrtag }}/druidscornerapi-base:${{ inputs.imgtag }}

  - name: Publish image
    run : |
      docker push ${{ inputs.gcrtag }}/druidscornerapi-base:${{ inputs.imgtag }}
    