# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Docker build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'DruidsCornerAPI/**'
  
  pull_request:
    branches: [ "main" ]
    paths:
      - 'DruidsCornerAPI/**'

  workflow_dispatch :
    inputs:
      build_base:
        description: 'Build the base image as well'
        required: true
        default: false
        type: boolean
      
      force_publish:
        description: 'Bypasses main branch check and forces deploy image publication to GCS.'
        required: true
        default: false
        type: boolean
env:
  BUCKET_DBPATH: ${{ secrets.DRUIDS_CORNER_CLOUD_BUCKET_DBPATH }}
  CONTAINER_REG_ZONE : europe-docker.pkg.dev
  CONTAINER_REGISTRY : druidscornercloud-registry
  GCP_PROJECT_ID : druids-corner-cloud
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Authenticate docker with GCloud
      run: |
        printf '%s' '${{ secrets.DRUIDS_CORNER_CLOUD_CICD_SA_KEYFILE }}' > keyfile.json
        gcloud auth activate-service-account '${{ secrets.DRUIDS_CORNER_CLOUD_CICD_SA }}' --key-file=keyfile.json
        gcloud auth configure-docker $CONTAINER_REG_ZONE

    - name: Authenticate docker against Github 
      run: |        
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor}} --password-stdin

        
    - name: Build base image
      uses: "./.github/template/base_image"
      if: github.event.inputs.build_base == 'true'
      with:
        dbpath: $BUCKET_DBPATH
        ghcrtag: ghcr.io/${{ github.actor }}/druidscornerapi-base
        imgtag : $IMAGE_TAG
        keyfile: ${{ secrets.DRUIDS_CORNER_CLOUD_CICD_SA_KEYFILE }}

    - name: Build Docker image (with UnitTests)
      working-directory: DruidsCornerAPI 
      run : |
        echo '${{ secrets.DRUIDS_CORNER_CLOUD_AUTHCONFIGJSON }}' > DruidsCornerAPI/.config/AuthenticationConfig.json
        docker build -f Dockerfile.deploy --target build . -t druidscornerapi-build

    - name: Test
      run: docker run --name testing_container druidscornerapi-build  "dotnet" "test" "DruidsCornerUnitTests" "-l:junit" "-c" "Release" 

    - name: Retrieve tests results
      run: docker cp testing_container:DruidsCornerAPI/DruidsCornerUnitTests/TestResults/TestResults.xml TestResults.xml

    - name: Archive Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults.xml
    
    - name: Build Docker image for deployment (stripped down version)
      working-directory: DruidsCornerAPI 
      run : |
        echo '${{ secrets.DRUIDS_CORNER_CLOUD_AUTHCONFIGJSON }}' > DruidsCornerAPI/.config/AuthenticationConfig.json
        docker build -f Dockerfile.deploy . -t druidscornerapi-deploy
        docker tag druidscornerapi-deploy $CONTAINER_REG_ZONE/$GCP_PROJECT_ID/$CONTAINER_REGISTRY/druidscornerapi-deploy:$IMAGE_TAG
    
    - name: Publish image
      if: ( github.event.inputs.force_publish == 'true' ) || ( github.ref == 'refs/heads/main' )
      run : |
        docker push $CONTAINER_REG_ZONE/$GCP_PROJECT_ID/$CONTAINER_REGISTRY/druidscornerapi-deploy:$IMAGE_TAG
        
        
      
    